### ISSUE TITLE
Create a new iframe to embed on a webpage

### ISSUE THREAD

**Issue by Fish360** [Fish360/Journal#14]
#### Summary
The Fish360 Journal is hosted at heroku.  Angler will access it from another webpage.  Hence, we need to create an iFrame to embed on another webpage.

We created an iFrame for when the Fish360 Journal was hosted at Red Hat Open Shift.  Perhaps we just need to update the URL?

**Comment by Fish360** [comment]
@jannunzi 

What are the sub-tasks / details for this task?

**Comment by Fish360** [comment]
@patelankita 

This is a critical one! 

Thank you in advance!!!

**Comment by yashsnehalshah** [comment]
Hey Julio @Fish360 

I had a word with professor. This is the iframe snippet:

<body>
<iframe src="https://fish360.herokuapp.com/#/" height="600" width="300"></iframe>
</body>

The height and width have been selected so as to support normal Iphone users.

It would look like this:

![fishiframe](https://user-images.githubusercontent.com/22141408/36007429-62fe656e-0d10-11e8-976e-e3e7d160767a.JPG)

I want to know which is the target page in which this iframe has to be embedded? Can i have access to that?

Thanks

**Comment by yashsnehalshah** [comment]
@Fish360 Sorry i didn't refresh the page before posting the above comment. Didn't knew it was unassigned to me. Apologies. @patelankita can take from here.

**Comment by Fish360** [comment]
We are a TEAM.
No worries

@yashsnehalshah

**Comment by Fish360** [comment]
I added the iframe to a webpage and got this error. 

![iframe_error](https://user-images.githubusercontent.com/2513400/36008348-e1362102-0d14-11e8-85f1-292138c928eb.png)

**Comment by Fish360** [comment]
Jose,

Here is the iFrame code that I used on the webpage:

![iframe_code](https://user-images.githubusercontent.com/2513400/36057187-545cd652-0dd9-11e8-9411-eaa47d7c6cea.png)

@jannunzi

**Comment by yashsnehalshah** [comment]
Hi Julio @Fish360 ,

It should have worked. I am not sure why it didn't.

This is a plain HTML code i wrote:

<!DOCTYPE html>
<html>
<head>
<title>Testing</title>
</head>
<body>

<iframe src="https://fish360.herokuapp.com/" height="600" width="300"></iframe>
</body>
</html>

And here is the screen:
![error](https://user-images.githubusercontent.com/22141408/36057567-ab4ad91a-0ddd-11e8-8d09-2d01bb43873d.JPG)

Can you try once with this snippet:

<iframe src="https://fish360.herokuapp.com/" height="600" width="300"></iframe>

**Comment by yashsnehalshah** [comment]
The page source from my html:

![image](https://user-images.githubusercontent.com/22141408/36057620-36ea507c-0dde-11e8-9101-d878de417359.png)

**Comment by Fish360** [comment]
Using a Chrome browser, I went directly to: https://fish360.herokuapp.com/#

1. I cannot log in.
2. The Register form does not display.
3. The Forgot Password page does not display

I.e., no function on this page works. :-(

Hence, I do not think the issue is in the iFrame code itself.

@yashsnehalshah @patelankita @jannunzi

**Comment by yashsnehalshah** [comment]
We are looking into that @Fish360 

I performed the same functions on Chrome browser and was able to register and login.

I clicked on "Forgot Password" and it did redirect(though it didn't send me a new password on my registered email-id)

I will ask Ankita to test once on her machine.

**Comment by patelankita** [comment]
@Fish360  @yashsnehalshah 
The login and register functionality were not working for me yesterday.. But today i tried again and it works. Which is strange! I am trying to figure out the weird behavior.

**Comment by patelankita** [comment]
@Fish360 
Julio can you please check if the login and register functionality are working for you now. I checked the logs on heroku and they seem to be working fine now. There was one small fix with the 'logout' functionality, i have corrected the redirection to 'login' page. 

 If everything works fine for you then i can create a merge request for this issue.

**Comment by Fish360** [comment]
@patelankita,

Still seeing errors.  But, the register pages comes ups now.  

Send me an email (juliosilva@fish360.net) and we can coordinate a time tomorrow for an online meeting.  I will share my screen and show you what I am seeing.

**Comment by Fish360** [comment]
#### 01-MAR-2018 Meeting Minutes

* Login with existing user account failed. :-(
* Creation of new user account worked! :-)

**Comment by Fish360** [comment]
Re-tested and confirmed fixed on via Chrome browser on Win10 machine.

Closing.

@patelankita
