### ISSUE TITLE
Add Weather to Spot

### ISSUE THREAD

**Issue by Fish360** [Fish360/Journal#38]

**Comment by patelankita** [comment]
Hey Julio @Fish360,
 Can I start working on this issue, while you assign us the tasks for Sprint 2?

**Comment by Fish360** [comment]
@patelankita 

Ankita,

Yes.

Assigned.

**Comment by Fish360** [comment]
@jannunzi,

We need a way to decouple the weather/tide service such that the code reads in the API information from a file.

This will allow different installations of the Fish360 Journal to specify what tide/weather API to use.

Has this already been done or do we need a new ticket?

**Comment by patelankita** [comment]
@Fish360 Julio, I have a question. The spot doesn't have a field for the Date. And for the weather to be displayed, we need the current date and longitude and latitude. So should I  first add the date field to the spot? Please correct me if I am understanding it wrong.

**Comment by Fish360** [comment]
@patelankita 

You are correct!

Let's add a Date field to the Weather region on the spot.

The default value of the Date field is the current day.

**Comment by patelankita** [comment]
@Fish360 Perfect i have implemented it with the default value as the current day. I am getting a small bug currently, but will resolve it and create a pull request by EOD.

**Comment by patelankita** [comment]
@Fish360 Julio, since morning I am not able to access the weather API. It gives the following error on the console.
<img width="1415" alt="screen shot 2018-04-10 at 2 12 18 pm" src="https://user-images.githubusercontent.com/22179341/38575392-4d2eb746-3cc9-11e8-946f-84f0aa6371e0.png">

On opening the link in browser it shows - "API key has been disabled".

<img width="966" alt="screen shot 2018-04-10 at 2 12 07 pm" src="https://user-images.githubusercontent.com/22179341/38575468-77bb042e-3cc9-11e8-8c79-7cfaecd10e56.png">

The functionality has been implemented, but am not able to put up the screen shots because of the API error. I will talk to the professor as well about this. Please let me know if you know of any way to resolve this. 

Thanks,
Ankita

**Comment by Fish360** [comment]
@patelankita 

Ankita, 

There is an issue with the API provider. 
I am in communication with their tech support. It will be resolved soon'ish.

**Comment by patelankita** [comment]
@Fish360 Thank you Julio. I will post the screen shots of the added funcitonality as soon as the API starts working.

**Comment by Fish360** [comment]
@patelankita 

The issue with the Weather/Tide API service has been resolved.  The API should be returning data now, or very soon.

**Comment by patelankita** [comment]
@Fish360 Julio,
 I am still getting the same error. API key disabled.

**Comment by Fish360** [comment]
@patelankita 

Ankita,

:-(

I will follow up again with the service provider.

**Comment by Fish360** [comment]
#### Test Result

Failed testing.  
Renewing the API license did not resolve the issue.
Requires investigation.
